# -*- coding: utf-8 -*-
NAME = "Estadistica Inferencial"

# EJE CLINICO: del PROBLEMA al concepto.
EJES = [
  ("Estudié 80 pacientes, ¿qué puedo afirmar de todos los pacientes?", [
    ("Tomar un subconjunto que represente a la población",
     "Muestreo"),
    ("La distribución de un estadístico (p.ej. la media) entre muestras",
     "Distribución muestral"),
    ("Cuánto varía mi ESTIMACIÓN de muestra a muestra",
     "Error estándar (SE = SD/√n)"),
    ("El rango plausible donde está el valor real de la población",
     "Intervalo de confianza (IC) — herramienta: scipy.stats"),
  ]),
  ("El grupo tratado mejoró más, ¿es real o pura casualidad?", [
    ("La hipótesis de 'no hay efecto / no hay diferencia'",
     "Hipótesis nula (H₀)"),
    ("La probabilidad de datos así de extremos SI H₀ fuera cierta",
     "Valor p"),
    ("El umbral con que decido rechazar H₀ (típico 0.05)",
     "Nivel de significancia (α)"),
    ("Rechazar H₀ cuando en realidad era cierta (falso positivo)",
     "Error tipo I"),
    ("No rechazar H₀ cuando era falsa (falso negativo)",
     "Error tipo II"),
    ("La capacidad de detectar un efecto que sí existe",
     "Potencia (1 − β)"),
  ]),
  ("¿Qué prueba uso para comparar mis grupos?", [
    ("Comparar las medias de dos grupos (continua, normal)",
     "t de Student"),
    ("Comparar las medias de 3 o más grupos",
     "ANOVA"),
    ("Comparar proporciones / categóricas en una tabla 2×2",
     "Chi-cuadrada"),
    ("Comparar dos grupos cuando NO se cumple normalidad",
     "Mann-Whitney (no paramétrica)"),
    ("Decidir entre paramétrico y no paramétrico",
     "Verificar supuestos (normalidad, varianzas iguales) — scipy.stats, pingouin"),
  ]),
  ("Quiero saber qué factores predicen un desenlace (p.ej. mortalidad)", [
    ("Predecir un desenlace continuo a partir de variables",
     "Regresión lineal"),
    ("Predecir un desenlace binario (vivo/muerto, sí/no)",
     "Regresión logística"),
    ("La medida de efecto que entrega la logística",
     "Odds ratio (OR)"),
    ("Cuánta varianza del desenlace explica el modelo",
     "R²"),
    ("Quitar el efecto de una confusora del estimado",
     "Ajuste / control por covariables"),
    ("Revisar que el modelo cumple sus supuestos",
     "Análisis de residuales — herramienta: statsmodels"),
  ]),
  ("Tengo varios estudios sobre lo mismo, ¿cómo los combino? (meta-análisis)", [
    ("Una medida estandarizada de la magnitud del efecto",
     "Tamaño de efecto"),
    ("Dar más peso a los estudios más precisos",
     "Ponderación por inverso de la varianza"),
    ("Asumir un único efecto verdadero común a todos",
     "Modelo de efectos fijos"),
    ("Asumir una distribución de efectos entre estudios",
     "Modelo de efectos aleatorios"),
    ("Cuánto varían los resultados entre estudios",
     "Heterogeneidad (Q, I²)"),
    ("Ver el efecto y su IC estudio por estudio",
     "Forest plot"),
    ("Detectar sesgo de publicación",
     "Funnel plot (nota: metafor de R es el estándar de oro)"),
  ]),
  ("(radar) Capas siguientes, cuando un problema te empuje", [
    ("Tiempo hasta que ocurre un evento (supervivencia)",
     "Kaplan-Meier / Cox (lifelines)"),
    ("Actualizar priors con datos de forma formal",
     "Estadística bayesiana (PyMC)"),
    ("Muchas pruebas a la vez inflan los falsos positivos",
     "Corrección por comparaciones múltiples / p-hacking"),
  ]),
]

# INTEGRADOR: de las SENALES concretas al concepto + tip verbalizable.
ESTACIONES = [
  ("ESTIMACIÓN Y ERROR", [
    ("Describe cuánto varía mi ESTIMACIÓN, no los datos",
     "Se encoge cuando n crece (se divide entre √n)",
     "SE = SD / √n",
     "Error estándar (SE)",
     "la SD describe los datos; el SE describe la confianza en mi estimación"),
    ("Es el rango plausible del valor real de la población",
     "Más n lo hace más estrecho",
     "Si NO incluye el valor nulo, entonces p &lt; 0.05",
     "Intervalo de confianza",
     "el IC y la prueba de hipótesis son la misma cosa vista de dos formas"),
    ("Confundirlos es de los errores más comunes",
     "Uno describe los datos, el otro la estimación",
     "Se relacionan por SE = SD/√n",
     "SD vs SE",
     "SD = dispersión de los datos; SE = dispersión de la media; parientes por √n"),
  ]),
  ("LA TRAMPA DEL VALOR P", [
    ("Es P(datos así de extremos | H₀ cierta)",
     "NO es la probabilidad de que H₀ sea falsa",
     "NO mide el tamaño ni la importancia del efecto",
     "Valor p",
     "el p responde '¿qué tan raros son mis datos si no hubiera efecto?', no '¿qué tan probable es que me equivoque?'"),
    ("Rechazo H₀ cuando en realidad era cierta",
     "Es un falso positivo",
     "Su probabilidad es α (típico 0.05)",
     "Error tipo I",
     "tipo I = grito 'hay efecto' cuando no lo hay"),
    ("Un p significativo con n enorme puede ser trivial",
     "Significancia estadística ≠ relevancia clínica",
     "El tamaño de efecto dice si IMPORTA",
     "Significancia vs relevancia",
     "separa siempre '¿es real?' (p) de '¿importa?' (tamaño de efecto)"),
  ]),
  ("ELEGIR LA PRUEBA", [
    ("Desenlace continuo, dos grupos, datos normales",
     "Compara dos medias",
     "Si falla la normalidad, usa Mann-Whitney",
     "t de Student",
     "t para comparar dos medias continuas y normales"),
    ("Variables categóricas en una tabla 2×2",
     "Compara frecuencias observadas vs esperadas",
     "Es el nodo central de la tabla 2×2",
     "Chi-cuadrada",
     "chi-cuadrada vive en la tabla 2×2, igual que sens/spec y el odds ratio"),
    ("Desenlace binario (vivo/muerto)",
     "Su coeficiente se lee como odds ratio",
     "Modela una probabilidad",
     "Regresión logística",
     "la logística predice un sí/no y entrega odds ratios clínicos"),
  ]),
  ("COMBINAR ESTUDIOS (META-ANÁLISIS)", [
    ("Los estudios más precisos pesan más",
     "El peso es el INVERSO de la varianza",
     "La misma varianza de probabilidad, ahora como peso",
     "Ponderación por inverso de varianza",
     "el estudio con menos varianza (más preciso) manda más en el promedio combinado"),
    ("Mide cuánto discrepan los estudios entre sí",
     "Un I² alto significa que no concuerdan",
     "Decide entre efectos fijos y aleatorios",
     "Heterogeneidad (I²)",
     "I² alto: los estudios cuentan historias distintas → usa efectos aleatorios"),
    ("Asume un único efecto verdadero común a todos",
     "Se contrasta con el modelo de efectos aleatorios",
     "Se elige según la heterogeneidad",
     "Efectos fijos vs aleatorios",
     "fijos: un solo efecto real; aleatorios: cada estudio mide un efecto algo distinto"),
  ]),
]
