# -*- coding: utf-8 -*-
# Contenido derivado del curso "Statistics and Probability" de Khan Academy
# (khanacademy.org/math/statistics-probability), 16 unidades, estilo AP Statistics.
# Misma metodologia de ejes que probabilidad/descriptiva/inferencial/prob_mit.
NAME = "Estadistica Khan"

# EJE CLINICO: del PROBLEMA (en voz del que aprende) al concepto que nace.
EJES = [
  ("Tengo datos de categorías (no números): ¿cómo los resumo y cruzo?", [
    ("Distinguir una variable de categorías de una numérica",
     "Variable categórica vs cuantitativa"),
    ("Mostrar las frecuencias de cada categoría",
     "Gráfico de barras / circular (pie)"),
    ("Cruzar dos variables categóricas en una tabla",
     "Tabla de doble entrada (two-way table)"),
    ("Los totales al margen de la tabla",
     "Distribución marginal"),
    ("La distribución de una variable DENTRO de un nivel de la otra",
     "Distribución condicional"),
    ("Ver si dos categóricas se asocian",
     "Comparar las distribuciones condicionales (frecuencias relativas)"),
  ]),
  ("Tengo datos numéricos: ¿cómo veo su forma?", [
    ("Mostrar la distribución con barras de intervalos",
     "Histograma"),
    ("La forma general (simétrica o sesgada)",
     "Shape / sesgo (skew)"),
    ("Rasgos: agrupamientos, huecos, picos, atípicos",
     "Clusters, gaps, peaks, outliers"),
    ("Comparar dos distribuciones",
     "Comparar forma + centro + dispersión (siempre en contexto)"),
  ]),
  ("¿Cuál es el centro y cuánto se dispersan los datos?", [
    ("El centro que reparte la masa (sensible a extremos)",
     "Media"),
    ("El centro que parte la muestra en dos (resiste extremos)",
     "Mediana"),
    ("El rango entre el cuartil 1 y el 3",
     "Rango intercuartílico (IQR = Q3 − Q1)"),
    ("La dispersión promedio al cuadrado respecto a la media",
     "Varianza"),
    ("Su raíz, en las unidades originales",
     "Desviación estándar (SD)"),
    ("Por qué al estimar la varianza desde una muestra divido entre n−1",
     "Corrección de Bessel (estimador insesgado)"),
    ("Resumir 5 números en una caja y marcar atípicos",
     "Boxplot + regla del 1.5×IQR"),
  ]),
  ("¿Dónde cae un valor respecto al resto, y cómo modelo la distribución?", [
    ("El porcentaje de datos que queda por debajo de un valor",
     "Percentil"),
    ("A cuántas desviaciones estándar está de la media",
     "z-score = (x − μ)/σ"),
    ("Qué pasa con media y SD al sumar/multiplicar a todos los datos",
     "Transformaciones lineales (sumar corre el centro; multiplicar escala todo)"),
    ("Una curva continua cuya área total es 1",
     "Curva de densidad"),
    ("La campana definida por μ y σ",
     "Distribución normal"),
    ("Repartir 68-95-99.7% en la normal",
     "Regla empírica"),
    ("Hallar proporciones bajo la normal",
     "Estandarizar a Z + tabla normal"),
  ]),
  ("Dos variables numéricas: ¿se relacionan?", [
    ("Graficar los pares (x, y)",
     "Diagrama de dispersión (scatterplot)"),
    ("Describir la nube de puntos",
     "Forma, dirección, fuerza y atípicos"),
    ("Un número entre −1 y 1 que mide la relación LINEAL",
     "Coeficiente de correlación r"),
    ("La recta que minimiza la suma de errores al cuadrado",
     "Regresión de mínimos cuadrados (least-squares)"),
    ("La diferencia entre el valor real y el predicho",
     "Residual (observado − predicho)"),
    ("Ver si la recta es un buen modelo",
     "Gráfico de residuales (patrón = mal ajuste)"),
    ("La fracción de la variación explicada por la recta",
     "R² (coeficiente de determinación)"),
  ]),
  ("¿Cómo recojo los datos sin engañarme?", [
    ("Una pregunta que espera variabilidad en las respuestas",
     "Pregunta estadística"),
    ("Cuando la muestra no representa a la población",
     "Sesgo (bias)"),
    ("Elegir al azar para que la muestra represente",
     "Muestreo aleatorio simple"),
    ("Solo observar vs intervenir asignando tratamiento",
     "Estudio observacional vs experimento"),
    ("Lo que permite hablar de CAUSA",
     "Asignación aleatoria del tratamiento (+ grupo control)"),
  ]),
  ("Quiero ponerle número al azar", [
    ("Probabilidad por conteo de casos en un modelo",
     "Probabilidad teórica"),
    ("Probabilidad por frecuencia observada al repetir",
     "Probabilidad experimental"),
    ("Probabilidad de A o B",
     "Regla de la suma: P(A)+P(B)−P(A∩B)"),
    ("Probabilidad de A y B si son independientes",
     "Regla del producto: P(A)·P(B)"),
    ("Probabilidad de A y B si son dependientes",
     "Regla general: P(A)·P(B|A)"),
    ("La probabilidad de A sabiendo que ocurrió B",
     "Probabilidad condicional P(A|B)"),
  ]),
  ("¿De cuántas formas puede ocurrir algo?", [
    ("Multiplicar las opciones de cada paso",
     "Principio fundamental del conteo"),
    ("Elegir/ordenar k de n cuando el orden SÍ importa",
     "Permutaciones"),
    ("Elegir k de n cuando el orden NO importa",
     "Combinaciones"),
  ]),
  ("Una variable cuyo valor es aleatorio", [
    ("El valor promedio ponderado por probabilidad",
     "Valor esperado E[X] = Σ x·P(x)"),
    ("La media de la suma o la diferencia de dos variables",
     "Se suma/resta directo: E[X±Y] = E[X] ± E[Y]"),
    ("La varianza de la suma O de la diferencia (si son independientes)",
     "SIEMPRE se SUMAN las varianzas"),
    ("Contar éxitos en un número fijo n de intentos",
     "Binomial (media np, SD √(np(1−p)))"),
    ("Cuántos intentos hasta el primer éxito",
     "Geométrica"),
    ("Asumir independencia al muestrear sin reemplazo",
     "Condición del 10% (n ≤ 10% de la población)"),
  ]),
  ("¿Cómo varía un estadístico de muestra a muestra?", [
    ("La distribución de un estadístico sobre todas las muestras posibles",
     "Distribución muestral"),
    ("Un estimador cuya media es el parámetro",
     "Estimador insesgado"),
    ("La desviación estándar de la media muestral",
     "Error estándar SE = σ/√n"),
    ("Por qué la media muestral se vuelve normal aunque los datos no lo sean",
     "Teorema del Límite Central (TLC)"),
  ]),
  ("Quiero estimar un parámetro con un rango", [
    ("Un rango plausible para el parámetro",
     "Intervalo de confianza (estimación ± margen)"),
    ("Cuánto sumo/resto a la estimación",
     "Margen de error = valor crítico · SE"),
    ("El multiplicador según el nivel de confianza",
     "Valor crítico z* (proporción) o t* (media)"),
    ("Cuándo uso t en vez de z para la media",
     "Cuando σ es desconocida (casi siempre)"),
    ("Verificar que el intervalo es válido",
     "Condiciones: aleatorio · normal o n grande · 10%"),
  ]),
  ("¿La evidencia contradice una afirmación?", [
    ("La afirmación de 'no hay efecto' que intento refutar",
     "Hipótesis nula H0"),
    ("Lo que sostengo si rechazo H0",
     "Hipótesis alternativa Ha"),
    ("Probabilidad de ver datos tan extremos SI H0 fuera cierta",
     "Valor p"),
    ("Rechazar H0 siendo verdadera (falsa alarma)",
     "Error tipo I (probabilidad α)"),
    ("No rechazar H0 siendo falsa (no detectar lo real)",
     "Error tipo II (probabilidad β)"),
    ("Probabilidad de detectar un efecto que sí existe",
     "Potencia (1 − β)"),
  ]),
  ("Quiero comparar dos grupos", [
    ("La diferencia entre dos proporciones",
     "IC / test z para p1 − p2"),
    ("La diferencia entre dos medias",
     "IC / test t para μ1 − μ2"),
    ("Comparar antes vs después en los mismos sujetos",
     "Datos pareados (t de la diferencia)"),
  ]),
  ("Datos categóricos: ¿encajan con lo esperado o se asocian?", [
    ("Comparar conteos observados con una distribución esperada",
     "Chi-cuadrado de bondad de ajuste (GOF)"),
    ("Ver si dos categóricas se asocian en una tabla",
     "Chi-cuadrado de independencia / homogeneidad"),
    ("El estadístico que mide el desajuste",
     "χ² = Σ (observado − esperado)² / esperado"),
  ]),
  ("Inferencia y modelos de regresión más allá de lo básico", [
    ("Probar si la pendiente verdadera de la regresión es 0",
     "Test t para la pendiente"),
    ("Datos curvos que quiero ajustar con una recta",
     "Transformar los datos (log, raíz...) para linealizar"),
    ("Comparar MÁS de dos medias a la vez",
     "ANOVA (estadístico F)"),
    ("Descomponer la variación total en entre y dentro",
     "SST = SSB (entre grupos) + SSW (dentro)"),
  ]),
]

# INTEGRADOR: de las SENALES concretas (discriminadores) al concepto + tip verbalizable.
ESTACIONES = [
  ("DISTRIBUCIONES EN TABLAS", [
    ("Son los totales al borde de la tabla de doble entrada",
     "Ignoran la otra variable",
     "Se leen 'del total general'",
     "Distribución marginal",
     "la marginal mira una variable sola, sobre el total general"),
    ("Se calcula DENTRO de una fila o columna fija",
     "Depende del nivel de la otra variable",
     "Comparar varias condicionales revela si hay asociación",
     "Distribución condicional",
     "la condicional vive dentro de un grupo; comparar condicionales muestra asociación"),
  ]),
  ("CENTRO Y DISPERSIÓN", [
    ("Usa todos los valores y se va hacia la cola del sesgo",
     "Es sensible a los valores atípicos",
     "En sesgo a la derecha queda por encima de la mediana",
     "Media",
     "la media persigue la cola del sesgo; el atípico la arrastra"),
    ("Es el valor del medio, parte la muestra en dos mitades",
     "Resiste atípicos y sesgo",
     "Si la distribución es sesgada, repórtala a ella",
     "Mediana",
     "la mediana aguanta extremos: el centro robusto"),
    ("Es Q3 − Q1, el ancho del 50% central",
     "Resiste atípicos, va de la mano de la mediana",
     "Se usa cuando los datos son sesgados",
     "IQR (rango intercuartílico)",
     "SD acompaña a la media (sensible); IQR acompaña a la mediana (robusto)"),
  ]),
  ("VARIANZA: n VS n−1", [
    ("Es la desviación estándar en las unidades originales",
     "Su cuadrado (varianza) está en unidades al cuadrado",
     "Es la que usa la regla empírica y la normal",
     "Desviación estándar",
     "la SD vuelve la dispersión a las unidades reales de los datos"),
    ("En una POBLACIÓN divides la suma de cuadrados entre N",
     "En una MUESTRA divides entre n−1",
     "El n−1 corrige el sesgo: si no, subestimarías la varianza poblacional",
     "Divisor de la varianza",
     "muestra: divide entre n−1 para no subestimar la varianza real"),
  ]),
  ("z-SCORE Y NORMAL", [
    ("Mide a cuántas SD de la media está un valor: (x−μ)/σ",
     "Es adimensional: permite comparar escalas distintas",
     "Convierte cualquier normal en la normal estándar",
     "z-score",
     "el z traduce cualquier valor a 'cuántas SD me alejo del centro'"),
    ("Reparte 68-95-99.7% a ±1, ±2 y ±3 SD de la media",
     "Solo vale para distribuciones normales",
     "Da un cálculo mental rápido sin tabla",
     "Regla empírica (68-95-99.7)",
     "la regla empírica reparte la campana: 68 a 1 SD, 95 a 2, 99.7 a 3"),
  ]),
  ("CORRELACIÓN Y REGRESIÓN", [
    ("Es un número entre −1 y 1",
     "Mide fuerza y dirección de la relación LINEAL",
     "Es adimensional; r = 0 no significa 'sin relación' (puede ser no lineal)",
     "Coeficiente de correlación r",
     "r mide solo lo lineal; cerca de ±1 fuerte, cerca de 0 nada lineal"),
    ("Minimiza la suma de los residuales al cuadrado",
     "Pasa por el punto (media de x, media de y)",
     "Predice y a partir de x",
     "Recta de mínimos cuadrados",
     "la recta de mínimos cuadrados es la que deja los errores² más chicos"),
    ("Es observado menos predicho por la recta",
     "Si su gráfico muestra un PATRÓN, la recta no es buen modelo",
     "Si está disperso al azar, la recta sirve",
     "Residual",
     "el residual es lo que la recta no explica; patrón en residuales = mal modelo"),
    ("Es la fracción de la variación de y explicada por la recta",
     "Va de 0 a 1 (o 0 a 100%)",
     "En regresión simple es r al cuadrado",
     "R² (coeficiente de determinación)",
     "R² = cuánto de la variación explica la recta; en simple es r²"),
  ]),
  ("DISEÑO Y CAUSALIDAD", [
    ("Solo observas y mides, no intervienes",
     "Puede haber variables de confusión",
     "Solo permite afirmar ASOCIACIÓN, no causa",
     "Estudio observacional",
     "observar solo da asociación: los confusores no se controlan"),
    ("Asignas el tratamiento a los sujetos AL AZAR",
     "El azar equilibra los confusores entre grupos",
     "Es lo único que permite hablar de CAUSA",
     "Experimento (asignación aleatoria)",
     "solo el experimento con asignación al azar permite afirmar causa"),
  ]),
  ("REGLAS DE PROBABILIDAD", [
    ("Sirve para P(A o B)",
     "Suma las dos y RESTA la intersección (contada dos veces)",
     "Si son mutuamente excluyentes, la intersección es 0",
     "Regla de la suma",
     "suma = 'o': sumo ambas y resto el solape"),
    ("Sirve para P(A y B)",
     "Si son independientes: P(A)·P(B)",
     "Si son dependientes: P(A)·P(B|A) (regla general)",
     "Regla del producto",
     "producto = 'y': encadeno, y si dependen uso la condicional P(B|A)"),
  ]),
  ("VARIABLES ALEATORIAS", [
    ("Es el promedio ponderado por probabilidad: Σ x·P(x)",
     "Es el centro a la larga",
     "Las medias se suman y se restan directo",
     "Valor esperado",
     "la media de una suma/resta es la suma/resta de las medias"),
    ("Al combinar dos variables independientes",
     "La varianza de la SUMA y la de la DIFERENCIA son iguales",
     "Las varianzas SIEMPRE se suman (la diferencia NO resta varianzas)",
     "Varianza de suma/diferencia",
     "medias se suman o restan; varianzas SIEMPRE se suman (si independientes)"),
    ("n fijo de intentos, cuenta cuántos éxitos",
     "vs esperar cuántos intentos hasta el primer éxito",
     "El primer caso es binomial; el segundo, geométrica",
     "Binomial vs geométrica",
     "binomial cuenta éxitos en n fijo; geométrica espera al primer éxito"),
  ]),
  ("DISTRIBUCIÓN MUESTRAL Y SE", [
    ("Es la distribución del ESTADÍSTICO, no la de los datos",
     "Se angosta a medida que n crece",
     "Su centro es el parámetro (si el estimador es insesgado)",
     "Distribución muestral",
     "no es la forma de los datos: es cómo varía el estadístico entre muestras"),
    ("Es la SD de la media muestral: σ/√n",
     "Baja al crecer n (por eso muestras grandes son más precisas)",
     "SD describe los datos; SE describe el estadístico",
     "Error estándar (SE)",
     "SE = σ/√n: la media muestral fluctúa menos que los datos"),
    ("La media muestral se vuelve normal",
     "Aunque la población NO sea normal",
     "Funciona si n es suficientemente grande",
     "Teorema del Límite Central",
     "el TLC es la bisagra: vuelve campana al promedio de cualquier dato"),
  ]),
  ("INFERENCIA: IC", [
    ("Es estimación ± (valor crítico · SE)",
     "Atrapa el parámetro con cierto nivel de confianza",
     "Más confianza o menos n lo hacen más ancho",
     "Intervalo de confianza",
     "el IC es la estimación rodeada de su margen de error"),
    ("Usa z* cuando es proporción (o σ conocida)",
     "Usa t* cuando es media con σ desconocida",
     "La t es más ancha: paga la incertidumbre extra de estimar σ",
     "z vs t",
     "z para proporciones; t para medias con σ desconocida (colas más gruesas)"),
  ]),
  ("TEST DE HIPÓTESIS", [
    ("H0 dice 'no hay efecto'; Ha es lo que sostienes",
     "Asumes H0 verdadera y mides qué tan raros son los datos",
     "Nunca 'aceptas' H0: solo la rechazas o no",
     "H0 vs Ha",
     "H0 = statu quo; el test solo decide si hay evidencia para rechazarla"),
    ("Es P(datos tan extremos | H0 verdadera)",
     "p pequeño = los datos serían raros bajo H0 → evidencia en contra",
     "NO es la probabilidad de que H0 sea verdadera",
     "Valor p",
     "p chico contradice H0; el p NO es P(H0 sea cierta)"),
    ("Rechazar H0 siendo verdadera es el error tipo I (α)",
     "No rechazarla siendo falsa es el error tipo II (β)",
     "Bajar α sube β: hay un intercambio",
     "Errores I y II",
     "tipo I = falsa alarma (α); tipo II = no detectar lo real (β)"),
  ]),
  ("CHI-CUADRADO Y ANOVA", [
    ("Compara conteos observados con los esperados",
     "Una sola variable categórica vs una distribución teórica",
     "Estadístico Σ(obs−esp)²/esp",
     "Chi-cuadrado de bondad de ajuste",
     "GOF = '¿los conteos encajan con la distribución esperada?'"),
    ("Trabaja sobre una tabla de doble entrada",
     "Independencia: UNA muestra, dos variables, ¿se asocian?",
     "Homogeneidad: VARIAS muestras, ¿misma distribución?",
     "Chi-cuadrado de independencia/homogeneidad",
     "tabla de dos vías: una muestra→independencia; varias→homogeneidad"),
    ("Compara MÁS de dos medias a la vez",
     "F = varianza ENTRE grupos / varianza DENTRO",
     "F grande → las medias difieren; SST = SSB + SSW",
     "ANOVA",
     "ANOVA pesa la varianza entre grupos contra la de dentro (F)"),
  ]),
]

# CAPA 2 - CONTRASTE: discriminar conceptos cercanos + supuestos/fallos.
# (tema, planteamiento, resolucion)
CONTRASTES = [
  ("Media vs Mediana (con sesgo)",
   "En una distribución sesgada, ¿cuál reportas y por qué?",
   "La media se deja arrastrar por la cola/atípicos; la mediana resiste. En sesgo a la derecha media &gt; mediana; "
   "a la izquierda media &lt; mediana. Con datos sesgados o con atípicos reporta la MEDIANA (y el IQR). Con datos "
   "simétricos sin atípicos, la media (y la SD)."),
  ("SD vs IQR",
   "Dos medidas de dispersión. ¿Cuándo cada una?",
   "La SD acompaña a la media: usa todos los datos y es SENSIBLE a atípicos. El IQR (Q3−Q1) acompaña a la mediana: "
   "es ROBUSTO. Regla práctica: si reportas media→SD; si reportas mediana (datos sesgados)→IQR."),
  ("Dividir entre N vs entre n−1",
   "¿Por qué la varianza muestral divide entre n−1 y no entre n?",
   "Con N (toda la población) divides entre N. Pero al estimar desde una MUESTRA, usar la media muestral hace que "
   "subestimes la varianza poblacional; dividir entre n−1 (grados de libertad) corrige ese sesgo y da un estimador "
   "INSESGADO. Por eso la 'varianza muestral' usa n−1."),
  ("Correlación vs Causalidad",
   "r es alto entre dos variables. ¿Una causa la otra?",
   "NO necesariamente. La correlación mide asociación lineal, no causa. Puede haber una variable de confusión o "
   "causalidad inversa. Solo un EXPERIMENTO con asignación aleatoria permite concluir causa. 'Correlation is not causation.'"),
  ("r vs R²",
   "¿Qué mide cada uno y cómo se relacionan?",
   "r ∈ [−1,1] mide fuerza y DIRECCIÓN de la relación lineal. R² ∈ [0,1] mide qué FRACCIÓN de la variación de y "
   "explica la recta. En regresión simple R² = r². r te dice el sentido; R² te dice cuánto explica el modelo."),
  ("Observacional vs Experimento",
   "¿Cuál permite afirmar causa-efecto?",
   "El observacional solo MIRA: da asociación, con confusores no controlados. El experimento ASIGNA el tratamiento "
   "al azar, equilibra los confusores y permite afirmar CAUSA. Si no hubo asignación aleatoria, no hables de causa."),
  ("Muestreo aleatorio vs Asignación aleatoria (alcance de la conclusión)",
   "Dos 'al azar' distintos. ¿Qué habilita cada uno?",
   "El MUESTREO aleatorio (elegir a quién observar) habilita GENERALIZAR a la población. La ASIGNACIÓN aleatoria "
   "(repartir tratamientos) habilita inferir CAUSA. Generalizar y causa son cosas distintas: necesitas el azar correcto para cada una."),
  ("Probabilidad teórica vs experimental",
   "¿En qué se diferencian?",
   "La teórica sale del MODELO (casos favorables / posibles, asumiendo simetría). La experimental sale de la "
   "FRECUENCIA observada al repetir. Por la ley de los grandes números, la experimental se acerca a la teórica al aumentar las repeticiones."),
  ("Independientes vs Mutuamente excluyentes",
   "Dos eventos que no pueden ocurrir juntos, ¿son independientes?",
   "NO. Mutuamente excluyentes (no coexisten) implica DEPENDENCIA: si ocurrió A, B tiene probabilidad 0. "
   "Independientes = no se informan (P(A∩B)=P(A)P(B)). Excluyente ≠ independiente: es la confusión clásica."),
  ("Eventos independientes vs dependientes (regla del producto)",
   "Para P(A y B), ¿cuándo multiplico simple y cuándo no?",
   "Independientes: P(A y B) = P(A)·P(B). Dependientes: P(A y B) = P(A)·P(B|A) (regla general), porque el primero "
   "cambia la probabilidad del segundo (ej: sacar cartas sin reemplazo). Pista: ¿el primer resultado cambia el segundo?"),
  ("Binomial vs Geométrica",
   "Ambas usan ensayos sí/no. ¿Cuándo cada una?",
   "Binomial: número FIJO n de intentos, cuentas CUÁNTOS éxitos. Geométrica: cuentas CUÁNTOS intentos hasta el "
   "PRIMER éxito (n no fijo). ¿Hay un n fijo y cuento éxitos? Binomial. ¿Espero al primer éxito? Geométrica."),
  ("var(X−Y): ¿se resta la varianza?",
   "Al restar dos variables independientes, ¿la varianza se resta?",
   "NO. var(X−Y) = var(X) + var(Y), igual que en la suma (si son independientes). Las MEDIAS se restan, pero las "
   "varianzas SIEMPRE se suman: restar añade incertidumbre, no la quita. Error muy común."),
  ("Distribución de los datos vs Distribución muestral",
   "¿Qué describe cada una?",
   "La distribución de los DATOS describe los valores individuales de una muestra/población. La distribución MUESTRAL "
   "describe cómo varía un ESTADÍSTICO (p.ej. la media) entre todas las muestras posibles. La muestral es más angosta y se "
   "estrecha al crecer n; es la base de toda la inferencia."),
  ("SD vs SE (error estándar)",
   "Se confunden constantemente. ¿Diferencia?",
   "La SD mide la dispersión de los DATOS individuales. El SE = σ/√n mide la dispersión de la MEDIA MUESTRAL "
   "(de la distribución muestral). El SE es más chico y baja con n; la SD no cambia con n. Reportar SE como si fuera SD subestima la variabilidad real."),
  ("z vs t",
   "¿Cuándo uso el estadístico z y cuándo el t?",
   "z: para proporciones, o para medias cuando σ poblacional es CONOCIDA (raro). t: para medias cuando σ es DESCONOCIDA "
   "y la estimas con s (lo habitual). La t tiene colas más gruesas (paga la incertidumbre de estimar σ) y se acerca a la z al crecer n."),
  ("Intervalo de confianza vs Test de hipótesis",
   "¿Qué responde cada uno?",
   "El IC ESTIMA: da un rango plausible para el parámetro. El test DECIDE: ¿hay evidencia contra un valor concreto (H0)? "
   "Están ligados: si el valor de H0 cae fuera del IC del nivel correspondiente, lo rechazas. El IC además dice la MAGNITUD, no solo si hay efecto."),
  ("Qué ES y qué NO es el valor p",
   "El p sale 0.03. ¿Qué significa exactamente?",
   "ES: P(observar datos tan extremos o más | H0 verdadera). NO ES: la probabilidad de que H0 sea verdadera, ni la "
   "probabilidad de equivocarte, ni el tamaño del efecto. p chico = los datos serían raros bajo H0, así que dudas de H0."),
  ("Error tipo I vs tipo II",
   "¿Cuál es cuál y cómo se relacionan?",
   "Tipo I: rechazar H0 siendo VERDADERA (falsa alarma), probabilidad α. Tipo II: NO rechazar H0 siendo FALSA "
   "(no detectar lo real), probabilidad β. La potencia es 1−β. Bajar α (ser más exigente) sube β: hay un trade-off."),
  ("Significancia estadística vs Relevancia clínica",
   "p &lt; 0.05, ¿entonces el efecto importa?",
   "No automáticamente. La significancia dice que el efecto probablemente NO es azar; no dice que sea GRANDE ni "
   "clínicamente importante. Con n enorme, efectos minúsculos salen significativos. Mira el TAMAÑO del efecto y su IC, no solo el p."),
  ("Chi-cuadrado: independencia vs homogeneidad vs GOF",
   "Tres pruebas chi-cuadrado. ¿Cómo las distingo?",
   "GOF: UNA variable categórica vs una distribución esperada (¿encaja?). Independencia: UNA muestra clasificada por "
   "DOS variables (¿se asocian?). Homogeneidad: VARIAS muestras/poblaciones, ¿la misma distribución de una variable? "
   "Independencia y homogeneidad usan tabla de dos vías y el mismo cálculo; cambia el diseño del muestreo."),
]
