# -*- coding: utf-8 -*-
# Contenido derivado del curso del MIT "Introduction to Probability" (RES.6-012,
# Spring 2018, John Tsitsiklis). Material: OCW (Parts I/II/III) + playlist YouTube.
# Misma metodologia de ejes que probabilidad/descriptiva/inferencial.
NAME = "Probabilidad MIT"

# EJE CLINICO: del PROBLEMA (en voz del que aprende) al concepto que nace.
EJES = [
  ("Algo es incierto: ¿cómo le pongo número a qué tan probable es?", [
    ("Listar TODOS los resultados posibles del experimento",
     "Espacio muestral Ω"),
    ("Quedarme con el subconjunto de resultados que me interesa",
     "Evento"),
    ("Asignar números que cumplan: no-negativos, total = 1, suman en disjuntos",
     "Axiomas de probabilidad"),
    ("Sumar la probabilidad de infinitos eventos disjuntos",
     "Aditividad contable"),
  ]),
  ("Ya sé que ocurrió algo: ¿cómo actualizo la probabilidad?", [
    ("La probabilidad de A sabiendo que ocurrió B",
     "Probabilidad condicional P(A|B) = P(A∩B)/P(B)"),
    ("Probabilidad de que A y B ocurran juntos",
     "Regla de la multiplicación"),
    ("Probabilidad total de B sumando sobre todas las causas posibles",
     "Teorema de probabilidad total"),
    ("Invertir el condicionamiento: pasar de P(B|A) a P(A|B)",
     "Regla de Bayes"),
  ]),
  ("¿Un evento informa sobre el otro?", [
    ("Que saber A no cambie la probabilidad de B",
     "Independencia: P(A∩B) = P(A)·P(B)"),
    ("Independencia que solo se cumple dado un tercer evento",
     "Independencia condicional"),
    ("Dos eventos que no pueden ocurrir juntos",
     "Mutuamente excluyentes (¡NO es independencia!)"),
  ]),
  ("¿De cuántas formas puede pasar algo?", [
    ("Multiplicar las opciones de cada etapa",
     "Principio de conteo"),
    ("Cuántas formas de elegir k de n SIN importar el orden",
     "Combinaciones C(n,k) = n! / (k!(n−k)!)"),
    ("Repartir n objetos en grupos de tamaños fijos",
     "Particiones / coeficiente multinomial"),
  ]),
  ("Quiero una variable cuyo valor sale al azar (discreta)", [
    ("Una función que asigna un número al resultado del experimento",
     "Variable aleatoria"),
    ("La probabilidad de cada valor posible",
     "PMF (función de masa) p_X(x)"),
    ("Un sí/no con probabilidad p",
     "Bernoulli"),
    ("Contar k éxitos en n intentos independientes",
     "Binomial"),
    ("Cuántos intentos hasta el primer éxito",
     "Geométrica"),
    ("El valor promedio que esperaría a la larga",
     "Valor esperado E[X] = Σ x·p(x)"),
    ("Calcular E[g(X)] sin hallar la distribución de g(X)",
     "Regla del valor esperado"),
  ]),
  ("¿Cuánto se dispersan los valores y cómo promedio por capas?", [
    ("La dispersión alrededor de la media",
     "Varianza var(X) = E[(X−μ)²] = E[X²] − μ²"),
    ("Que E[X+Y] = E[X] + E[Y] aunque NO sean independientes",
     "Linealidad de la esperanza"),
    ("Promediar dentro de cada caso y luego entre casos",
     "Teorema de la esperanza total"),
    ("Que la varianza de la suma sea la suma de varianzas",
     "Solo si son independientes: var(X+Y) = var X + var Y"),
  ]),
  ("Mi variable es continua", [
    ("La probabilidad como ÁREA bajo una curva",
     "Función de densidad PDF f(x)"),
    ("La probabilidad acumulada P(X ≤ x)",
     "Función de distribución CDF F(x)"),
    ("Tiempo de espera hasta un evento, sin memoria",
     "Exponencial"),
    ("La campana definida por su media y su desviación",
     "Normal; estandarizar a Z = (X−μ)/σ"),
  ]),
  ("Tengo dos variables continuas a la vez", [
    ("La densidad de X e Y juntas",
     "PDF conjunta f(x,y)"),
    ("Recuperar la densidad de una sola integrando la otra",
     "Marginal"),
    ("La densidad de X sabiendo que Y = y",
     "PDF condicional f(x|y)"),
    ("Bayes cuando mezclo una causa discreta con una observación continua",
     "Regla de Bayes mixta"),
  ]),
  ("Transformo una variable: ¿qué distribución tiene la nueva?", [
    ("La distribución de Y = g(X)",
     "Distribución derivada"),
    ("Caso en que g es monótona",
     "f_Y(y) = f_X(g⁻¹(y))·|d g⁻¹/dy|"),
  ]),
  ("Sumo variables y mido cómo se mueven juntas", [
    ("La densidad de la suma de dos independientes",
     "Convolución"),
    ("La suma de normales independientes",
     "Otra normal"),
    ("Cómo co-varían dos variables (signo de su relación)",
     "Covarianza cov(X,Y) = E[XY] − E[X]E[Y]"),
    ("La covarianza normalizada al rango [−1, 1]",
     "Coeficiente de correlación ρ"),
  ]),
  ("Promedio dentro de capas y junto azar con azar", [
    ("La esperanza de X vista como función de Y",
     "Esperanza condicional E[X|Y] (es una variable aleatoria)"),
    ("Promediar las esperanzas condicionales para recuperar el total",
     "Ley de esperanzas iteradas: E[E[X|Y]] = E[X]"),
    ("Descomponer la varianza en 'dentro' más 'entre'",
     "Ley de varianza total"),
  ]),
  ("Quiero estimar algo oculto a partir de datos (visión bayesiana)", [
    ("Tratar el parámetro como variable aleatoria con creencia previa",
     "Inferencia bayesiana (prior · verosimilitud → posterior)"),
    ("El valor del parámetro más probable a posteriori",
     "Estimador MAP"),
    ("El estimador que minimiza el error cuadrático medio",
     "LMS = E[X|Y]"),
    ("El mejor estimador LINEAL, usando solo medias, varianzas y covarianza",
     "LLMS (LMS lineal)"),
  ]),
  ("¿Por qué los promedios se estabilizan y se vuelven campana?", [
    ("Acotar la cola usando SOLO la media (variable no-negativa)",
     "Desigualdad de Markov"),
    ("Acotar la cola usando media y varianza",
     "Desigualdad de Chebyshev: P(|X−μ| ≥ k) ≤ σ²/k²"),
    ("El promedio muestral se acerca a la media verdadera al crecer n",
     "Ley débil de los grandes números (WLLN)"),
    ("El promedio (normalizado) se vuelve normal sin importar la distribución",
     "Teorema del Límite Central (TLC)"),
  ]),
  ("Inferencia clásica/frecuentista", [
    ("Parámetro fijo desconocido, estimarlo desde la muestra",
     "Inferencia clásica"),
    ("Elegir el parámetro que hace los datos observados más probables",
     "Máxima verosimilitud (MLE)"),
    ("Un rango que atrapa al parámetro con cierta confianza",
     "Intervalo de confianza"),
  ]),
  ("Eventos sí/no que se repiten en el tiempo (discreto)", [
    ("Secuencia de Bernoulli independientes a lo largo del tiempo",
     "Proceso de Bernoulli"),
    ("Tiempo hasta el primer éxito (sin memoria, fresh start)",
     "Geométrica"),
    ("Tiempo hasta el k-ésimo éxito",
     "Pascal (binomial negativa)"),
  ]),
  ("Eventos raros que llegan en tiempo continuo", [
    ("Llegadas aleatorias a tasa λ en tiempo continuo",
     "Proceso de Poisson"),
    ("Número de llegadas en un intervalo de duración t",
     "Poisson(λt)"),
    ("Tiempo entre llegadas / hasta la k-ésima",
     "Exponencial / Erlang"),
    ("Unir o separar procesos de Poisson",
     "Siguen siendo Poisson (tasas se suman / se reparten)"),
  ]),
  ("El futuro depende solo del presente", [
    ("El siguiente estado depende solo del actual, no del pasado",
     "Cadena de Markov (propiedad de Markov)"),
    ("Probabilidad de ir de i a j en n pasos",
     "Chapman-Kolmogorov (transiciones de n pasos)"),
    ("La distribución a largo plazo, independiente del inicio",
     "Distribución estacionaria (ecuaciones de balance)"),
    ("Estado del que ya no se sale, y prob de terminar ahí",
     "Estado absorbente / probabilidad de absorción"),
  ]),
]

# INTEGRADOR: de las SENALES concretas (discriminadores) al concepto + tip verbalizable.
ESTACIONES = [
  ("CONDICIONAL Y BAYES", [
    ("La probabilidad cambia porque ya sé que ocurrió otro evento",
     "Se calcula P(A∩B)/P(B): reescala al mundo donde B ya pasó",
     "Es la base del razonamiento diagnóstico",
     "Probabilidad condicional P(A|B)",
     "P(A|B) reescala la probabilidad al mundo donde B ya ocurrió"),
    ("Combina lo que creía antes (prior) con la evidencia (verosimilitud)",
     "Da vuelta la flecha del condicionamiento",
     "Convierte P(dato|causa) en P(causa|dato)",
     "Regla de Bayes",
     "Bayes invierte la flecha: de P(dato|causa) a P(causa|dato)"),
  ]),
  ("INDEPENDENCIA (las trampas)", [
    ("Saber que ocurrió A no cambia la probabilidad de B",
     "Se verifica con P(A∩B) = P(A)·P(B)",
     "NO es lo mismo que ser mutuamente excluyentes",
     "Independencia",
     "independientes = no se informan; excluyentes = no coexisten"),
    ("Cada par es independiente por separado",
     "Pero juntos NO necesariamente lo son",
     "Hay que verificar la condición sobre toda la colección",
     "Independencia por pares vs conjunta",
     "independencia por pares no garantiza independencia de todos juntos"),
    ("Con independencia E[XY] = E[X]·E[Y]",
     "Y la varianza de la suma se vuelve la suma de varianzas",
     "Sin independencia aparece el término de covarianza",
     "Independencia de variables aleatorias",
     "la independencia hace que esperanzas y varianzas se factoricen/sumen limpio"),
  ]),
  ("ESPERANZA Y VARIANZA", [
    ("Es el promedio ponderado por probabilidad: Σ x·p(x)",
     "Es lineal SIEMPRE: E[aX+b] = a·E[X] + b",
     "No requiere independencia para la suma",
     "Valor esperado E[X]",
     "la esperanza es el centro de masa de la distribución"),
    ("Mide la dispersión: E[(X−μ)²] = E[X²] − μ²",
     "Nunca es negativa",
     "var(aX+b) = a²·var(X): el +b no afecta, la escala va al cuadrado",
     "Varianza",
     "la varianza ignora el desplazamiento y escala con el cuadrado"),
    ("Calcula E[g(X)] = Σ g(x)·p(x)",
     "NO necesitas hallar la distribución de g(X)",
     "Aplica igual en el caso continuo con la integral",
     "Regla del valor esperado (LOTUS)",
     "para E[g(X)] pondero g(x); no necesito la distribución de g"),
  ]),
  ("DISCRETAS CLÁSICAS", [
    ("Cuenta éxitos en un número FIJO n de intentos",
     "Cada intento es Bernoulli(p) independiente",
     "Media np, varianza np(1−p)",
     "Binomial",
     "binomial = contar éxitos en n monedas"),
    ("Cuenta cuántos intentos hasta el PRIMER éxito",
     "Es sin memoria: lo ya esperado no cuenta",
     "Media 1/p",
     "Geométrica",
     "geométrica = la espera sin memoria del primer éxito"),
    ("Cuenta eventos raros por intervalo",
     "Su media es igual a su varianza (ambas λ)",
     "Es el límite de la binomial con n grande y p pequeño",
     "Poisson",
     "Poisson = contar eventos raros por unidad de tiempo; media = varianza"),
  ]),
  ("CONTINUAS Y DENSIDAD", [
    ("La probabilidad es el ÁREA bajo f(x), no la altura",
     "La probabilidad en un punto exacto es cero",
     "El área total bajo la curva es 1",
     "PDF (densidad)",
     "en lo continuo la probabilidad es área; un punto vale cero"),
    ("Acumula: F(x) = P(X ≤ x), crece de 0 a 1",
     "Su derivada es la densidad",
     "Sirve igual para discretas y continuas",
     "CDF (distribución acumulada)",
     "la CDF acumula; su pendiente es la densidad"),
    ("Modela el tiempo de espera hasta un evento",
     "Es sin memoria, como la geométrica pero continua",
     "Aparece como interllegada del proceso de Poisson",
     "Exponencial",
     "la exponencial es la espera sin memoria en tiempo continuo"),
  ]),
  ("COVARIANZA Y CORRELACIÓN", [
    ("E[XY] − E[X]E[Y]: su signo dice si suben juntas",
     "Depende de las unidades de X e Y",
     "Si son independientes vale 0 (pero 0 no implica independencia)",
     "Covarianza",
     "la covarianza dice la DIRECCIÓN del movimiento conjunto, en unidades crudas"),
    ("Es la covarianza normalizada: cov/(σ_X·σ_Y)",
     "Adimensional, entre −1 y 1",
     "Mide solo la relación LINEAL; ρ=0 no implica independencia",
     "Coeficiente de correlación ρ",
     "ρ normaliza la covarianza a [−1,1] y mide solo lo lineal"),
  ]),
  ("ITERAR ESPERANZA Y VARIANZA", [
    ("E[X|Y] es una variable aleatoria (función de Y)",
     "Promediarla sobre Y recupera E[X]",
     "Permite calcular por capas",
     "Ley de esperanzas iteradas",
     "promedio los promedios por capa y recupero el total"),
    ("Varianza total = promedio de las varianzas DENTRO de cada grupo",
     "Más la varianza ENTRE las medias de los grupos",
     "var(X) = E[var(X|Y)] + var(E[X|Y])",
     "Ley de varianza total",
     "la dispersión total = dispersión dentro de grupos + dispersión entre grupos"),
  ]),
  ("ESTIMACIÓN", [
    ("Minimiza el error cuadrático medio de la estimación",
     "Su solución es E[X|Y]",
     "Usa toda la distribución condicional",
     "LMS (Least Mean Squares)",
     "el mejor estimador en error cuadrático es la esperanza condicional"),
    ("Es el mejor estimador restringido a ser LINEAL en los datos",
     "Solo necesita medias, varianzas y covarianza",
     "Coincide con LMS cuando todo es normal",
     "LLMS (LMS lineal)",
     "LLMS es el LMS si te limitas a una recta: solo momentos de 2º orden"),
    ("Elige el parámetro que hace los datos observados más probables",
     "No usa prior: es la visión clásica",
     "Maximiza la verosimilitud",
     "Máxima verosimilitud (MLE)",
     "MLE: el parámetro bajo el cual lo que vi era lo más esperable"),
  ]),
  ("LÍMITES", [
    ("Acota la cola usando solo la media (variable ≥ 0)",
     "Es floja pero universal",
     "P(X ≥ a) ≤ E[X]/a",
     "Desigualdad de Markov",
     "Markov acota la cola con solo la media: tosca pero siempre vale"),
    ("Acota la cola usando media y varianza",
     "P(|X−μ| ≥ k) ≤ σ²/k²",
     "Es la base para probar la ley de los grandes números",
     "Desigualdad de Chebyshev",
     "Chebyshev acota cuánto te alejas del centro usando la varianza"),
    ("El promedio muestral converge a la media verdadera",
     "Cuando n crece, la dispersión del promedio tiende a 0",
     "Es convergencia en probabilidad",
     "Ley débil de los grandes números",
     "promediar muchas veces aplasta el azar hacia la media real"),
    ("El promedio (estandarizado) se vuelve normal estándar",
     "Sin importar la forma de la distribución original",
     "Funciona para n suficientemente grande",
     "Teorema del Límite Central",
     "el TLC es la bisagra: vuelve campana al promedio de CUALQUIER dato"),
  ]),
  ("PROCESOS EN EL TIEMPO", [
    ("Éxitos sí/no independientes en tiempo DISCRETO",
     "La interllegada es geométrica",
     "Tiene la propiedad de fresh start (arranca de cero en cualquier punto)",
     "Proceso de Bernoulli",
     "Bernoulli = monedas repetidas en el tiempo; espera geométrica"),
    ("Llegadas a tasa λ en tiempo CONTINUO",
     "El conteo en un intervalo es Poisson(λt); la interllegada es exponencial",
     "También tiene fresh start y memorylessness",
     "Proceso de Poisson",
     "el proceso de Poisson es el Bernoulli del tiempo continuo"),
    ("El siguiente estado depende solo del estado actual",
     "El pasado no añade información dado el presente",
     "A largo plazo la distribución no depende de dónde empezaste",
     "Cadena de Markov",
     "Markov: el presente borra el pasado para predecir el futuro"),
  ]),
]

# CAPA 2 - CONTRASTE: discriminar conceptos cercanos + supuestos/fallos.
# (tema, planteamiento, resolucion)
CONTRASTES = [
  ("Independientes vs Mutuamente excluyentes (la trampa)",
   "Dos eventos que no pueden ocurrir juntos, ¿son independientes?",
   "NO. Si son mutuamente excluyentes y ambos posibles, son DEPENDIENTES: saber que ocurrió A te dice "
   "que B no ocurrió (su probabilidad pasa a 0). Excluyente = no coexisten; independiente = no se informan. "
   "Es uno de los errores más comunes del curso."),
  ("P(A|B) vs P(A∩B)",
   "¿Qué distingue la probabilidad condicional de la conjunta?",
   "P(A∩B) es la probabilidad de que ocurran AMBOS, medida sobre todo el espacio. "
   "P(A|B) ya da por hecho B y mide A SOLO dentro del mundo B: por eso divide entre P(B). "
   "Relación: P(A∩B) = P(A|B)·P(B)."),
  ("P(dato|causa) vs P(causa|dato) — la condicional invertida",
   "Una prueba detecta bien la enfermedad. ¿Eso es lo mismo que: si doy positivo, estoy enfermo?",
   "NO, son condicionales invertidas. La sensibilidad es P(positivo|enfermo); lo que te importa es "
   "P(enfermo|positivo), que depende además de la prevalencia (el prior). Confundirlas es la falacia del fiscal. "
   "Bayes es la máquina que pasa de una a la otra."),
  ("PMF vs PDF",
   "Discreta y continua: ¿qué representa el valor de la función en un punto?",
   "En la PMF (discreta), p(x) ES la probabilidad de ese valor. En la PDF (continua), f(x) es una DENSIDAD: "
   "la probabilidad es el área (integral), y la de un punto exacto es 0. Por eso en continuo solo tienen "
   "sentido P(a ≤ X ≤ b)."),
  ("Permutaciones vs Combinaciones",
   "Elijo k de n elementos. ¿Importa el orden?",
   "Permutaciones: el orden SÍ importa (n!/(n−k)!). Combinaciones C(n,k): el orden NO importa, divides "
   "además entre k!. Pista: ¿'podio' (1º,2º,3º) o 'comité' (un grupo)? Podio = permutación; comité = combinación."),
  ("Covarianza vs Correlación",
   "Las dos miden si dos variables se mueven juntas. ¿Diferencia clave?",
   "La covarianza da la DIRECCIÓN pero en unidades crudas (no comparable entre pares). La correlación ρ la "
   "normaliza dividiendo entre σ_X·σ_Y: queda adimensional en [−1,1] y comparable. ρ mide solo relación LINEAL."),
  ("Correlación cero vs Independencia",
   "Si ρ = 0, ¿son independientes las variables?",
   "NO necesariamente. ρ=0 solo dice que no hay relación LINEAL; puede haber una relación no lineal fuerte "
   "(ej: Y = X² con X simétrica da ρ=0 pero son dependientes). Independencia implica ρ=0, pero no al revés."),
  ("Binomial vs Geométrica",
   "Ambas usan ensayos Bernoulli. ¿Cuándo cada una?",
   "Binomial: cuentas CUÁNTOS éxitos hay en un número FIJO n de intentos. Geométrica: cuentas CUÁNTOS intentos "
   "necesitas hasta el primer éxito (n no está fijado). Pista: ¿n fijo y cuento éxitos? Binomial. ¿Espero al primero? Geométrica."),
  ("Binomial vs Poisson",
   "Las dos cuentan eventos. ¿Cuándo cada una?",
   "Binomial: número FIJO de intentos sí/no con la misma p. Poisson: eventos raros por intervalo de tiempo/espacio, "
   "sin tope fijo, con media = varianza = λ. La Poisson es el límite de la binomial cuando n→∞, p→0 y np→λ."),
  ("Markov vs Chebyshev",
   "Dos cotas de cola. ¿Qué información usa cada una y cuál es más fina?",
   "Markov solo usa la media (y exige X ≥ 0): P(X ≥ a) ≤ E[X]/a, muy floja. Chebyshev usa media Y varianza: "
   "P(|X−μ| ≥ k) ≤ σ²/k², más fina porque la varianza acota cuánto te alejas. Chebyshev se deriva aplicando Markov a (X−μ)²."),
  ("WLLN vs TLC",
   "Ambos hablan del promedio de muchas muestras. ¿Qué dice cada uno?",
   "La ley de grandes números dice A DÓNDE va el promedio: converge a la media μ (un número). El TLC describe la FORMA "
   "de la fluctuación alrededor de μ: el promedio estandarizado se vuelve normal. LLN = puntería; TLC = la campana del error."),
  ("LMS vs LLMS",
   "Dos estimadores que minimizan error cuadrático. ¿Diferencia?",
   "LMS es el óptimo SIN restricciones: E[X|Y], puede ser cualquier función de los datos, pero necesita toda la "
   "distribución condicional. LLMS se restringe a funciones LINEALES y solo usa medias, varianzas y covarianza. "
   "Si todo es normal, LMS y LLMS coinciden."),
  ("Prior vs Posterior (bayesiano)",
   "En inferencia bayesiana, ¿qué distingue al prior del posterior?",
   "Prior: lo que creías del parámetro ANTES de ver los datos. Posterior: tu creencia DESPUÉS de incorporar la "
   "evidencia vía Bayes (prior × verosimilitud). El estimador MAP es el pico del posterior; el LMS es su media."),
  ("Bayesiano vs Clásico (frecuentista)",
   "¿El parámetro a estimar es aleatorio o fijo?",
   "Bayesiano: el parámetro es una VARIABLE ALEATORIA con un prior; se obtiene un posterior. Clásico/frecuentista: "
   "el parámetro es un número FIJO desconocido; no hay prior, se usan estimadores como MLE e intervalos de confianza. "
   "Por eso un intervalo de confianza NO es 'P(θ está dentro)=95%' en el sentido bayesiano."),
  ("Proceso de Bernoulli vs Proceso de Poisson",
   "Dos procesos de llegadas. ¿Qué los separa?",
   "Bernoulli vive en tiempo DISCRETO (ranuras): interllegada geométrica, conteo binomial. Poisson vive en tiempo "
   "CONTINUO: interllegada exponencial, conteo Poisson. El de Poisson es el límite continuo del de Bernoulli. "
   "Ambos comparten la propiedad de fresh start (sin memoria)."),
  ("¿Cuándo var(X+Y) = var X + var Y?",
   "La varianza de una suma, ¿siempre se suma?",
   "NO. En general var(X+Y) = var X + var Y + 2·cov(X,Y). El término de covarianza desaparece SOLO si X e Y son "
   "independientes (o al menos no correlacionadas). La esperanza sí es lineal siempre; la varianza no."),
]
